language: scala
jdk: openjdk8
scala:
  - 2.11.12
  - 2.12.10

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/9a1e2ef8-0b1f-11ea-97ff-ce88819b303b/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
